### ISSUE TITLE
Website info is erroneous

### ISSUE THREAD

**Issue by streaksu** [vlang/website#101]
The website claims the following chart:
```
Go    | 525 MB    | 1m 33s
Rust  | 30 GB     | 45m
GCC   | 8 GB      | 50m
Clang | 90 GB [0] | 25m
Swift | 70 GB [1] | 90m
V     | < 1 MB    | 0.15s - 0.6s
```

When this charts only hold true in debugging mode and taking into account the dependencies, as the quote for swift states, and for clang its just madness since that number refers to LLVM being compiled in debug mode.

This numbers are only relevant for developers, as this builds are not offered to outsiders of the project. If we want to put V in fair terms then, one has to add up `gcc` or `clang` to the size, as these are needed for build (using the same criteria as swift) as a bare minimum.

For example, a realistic number for a `rustc` install is 550 MB on disk, for `go` the 100 MB line is barely broken and `clang` just does not take that much space, in my system it takes 560 MB. Size of an install is evaluated depending on executables used by the user, not source builds with all the options that can make the size bigger enabled + dependencies.

**Comment by medvednikov** [comment]
This is about the size required to build from source and is taken from official sources.

V's default compiler is TCC now, it's a ~1 MB zip archive.
