### ISSUE TITLE
Bad detection of lanugage preferences

### ISSUE THREAD

**Issue by tobyjwebb** [vlang/website#105]
The language selector seems to have disappeared from the site, and now the language isn't detected correctly (it seems to be using geographical location for setting the language).

In my language preferences (in Firefox), I have set English (UK), English, and English (US) as my preferences, but as I am opening the page from Spain, it is detecting Spanish as my language. This is incorrect. Also, it is always a good idea to leave the language selector.

**Comment by JalonSolov** [comment]
The language selector is due to be brought back in the (hopefully) near future.
