### ISSUE TITLE
Links to V forum and V blog are dead

### ISSUE THREAD

**Issue by Kylebrown9** [vlang/website#106]
[blog.vlang.io/forum](blog.vlang.io/forum) and [blog.vlang.io](blog.vlang.io) are both dead at the current time and are referenced on the homepage

**Comment by tomByrer** [comment]
I suggest to close; website now links to:
https://forum.vlang.io
Which does work.
Forum & Twitter are the 'blog' for now.

**Comment by JalonSolov** [comment]
Discord is essentially the forum, these days.  The 'blog' as well.  However, the link to forum.vlang.io still needs to be removed or change to point to Discord.  Leaving this open until that is fixed.

**Comment by JalonSolov** [comment]
All the links on the page are currently working.
