### ISSUE TITLE
`docs.html` & vlang.io are out of sync

### ISSUE THREAD

**Issue by sarpik** [vlang/website#120]
Hello, it seems that docs.html & vlang.io are out of sync.
For example, the "Built-in ORM" example - some errors were fixed in https://github.com/vlang/website/pull/75, but the website currently does not incorporate them.

**Comment by JalonSolov** [comment]
ORM example was completely updated in PR #148 - just need to be deployed.

**Comment by medvednikov** [comment]
Deployed.
