### ISSUE TITLE
Automatic syntax highlighting of code

### ISSUE THREAD

**Issue by ntrel** [vlang/website#17]
I don't think it's sustainable to use manual markup for strings, comments, keywords, `&lt;`, and it makes editing the HTML difficult to read.

Can we use JavaScript to automatically highlight code examples? Or server side V? Alternatively we could use markdown instead of HTML for the docs.

**Comment by JalonSolov** [comment]
The current docs (https://github.com/vlang/v/blob/master/doc/docs.md) are in Markdown.
