### ISSUE TITLE
fast.vlang.io isn't working?

### ISSUE THREAD

**Issue by pklion** [vlang/website#190]
https://fast.vlang.io/
I think it is not working correctly...
It shows me the data which have too old timestamps.

**Comment by SlipperyDuck777** [comment]
This website is not supposed to give live data. It shows the data after each commit. However the timestamps are still incorrect. At the time of writing the most recent commit to [vlang/v](https://github.com/vlang/v) was 55c5b9c which was merged about 15 minutes ago. And yet the timestamp shows from July 4th.

Where the error might be:
Lines 76-79:
```v
	html_message := message.replace_each(['<', '&lt;', '>', '&gt;'])
	table =
		'<tr>
		<td>$date.format()</td>
```

**Comment by medvednikov** [comment]
Fixed: http://fast.vlang.io/

**Comment by medvednikov** [comment]
There were freebsd issues.

**Comment by pklion** [comment]
Thanks!
