### ISSUE TITLE
The playground of the v language official website does not work properly

### ISSUE THREAD

**Issue by tzSharing** [vlang/website#200]
The playground of the v language official website does not work properly.

**Comment by changrui** [comment]
Use `https://devbits.app/play` please.

**Comment by sanathusk** [comment]
is devbits.app/play maintained by anyone associated with Vlang.Can we get the source code to change it to choose V as default language instead of go

**Comment by sanathusk** [comment]
Also may be we can include the link to the updated playground in the v lang website,

**Comment by i582** [comment]
Try https://play.vlang.io
