### ISSUE TITLE
Responsiveness on /compare needs improvement

### ISSUE THREAD

**Issue by danawoodman** [vlang/website#217]
The way the layout is setup with CSS makes the compare page look pretty terrible on mobile because the max-width isn't being respected because of the parent element styling.

Related: is there  a plan to make the website not use a proprietary backend so it's easier to contribute improvements?

New V-fan here, excited to jump in 😄

**Comment by medvednikov** [comment]
> Related: is there a plan to make the website not use a proprietary backend so it's easier to contribute improvements?

Yes of course!

For now you'd have to use Chrome's dev tools and submit PRs with updated css.

**Comment by danawoodman** [comment]
I can't use dev tools to test out a change to `compare.html` since it extends from a template that doesn't exist (for example, all assets are missing). I'd be happy to submit a PR to fix this tho
