### ISSUE TITLE
V 0.3.2 is missing in Latest news

### ISSUE THREAD

**Issue by tedstoychev** [vlang/website#229]
At the moment news about [V 0.3.2](https://github.com/vlang/v/releases/tag/0.3.2) is missing in Latest news:

<img width="850" alt="Latest news" src="https://user-images.githubusercontent.com/1466111/199967520-653c1573-f132-46f8-9f63-072e2cd390cd.png">

Could an announcement about V 0.3.2 be added just like the ones for V 0.3.1 and V 0.3?

**Comment by i582** [comment]
Already fixed

<img width="644" alt="Снимок экрана 2023-01-08 в 17 33 26" src="https://user-images.githubusercontent.com/51853996/211198836-0d7c3443-9d31-4a53-8d7b-9e15aa73cd98.png">
