### ISSUE TITLE
Git is out of date with vlang.io

### ISSUE THREAD

**Issue by ntrel** [vlang/website#3]
E.g. https://vlang.io/docs#option has `You can also propagate errors` info, Git repo does not have this.

**Comment by medvednikov** [comment]
I'll push everything today and make sure it's always up-to-date from now on.

**Comment by medvednikov** [comment]
Done:

https://github.com/vlang/website/commit/7c397c95712d23f7bdd1848fe57efa4846e828d2

**Comment by ntrel** [comment]
Website is ahead of git again, e.g.:
https://vlang.io/docs#in
