### ISSUE TITLE
Language menu overlaps with doc headings

### ISSUE THREAD

**Issue by ntrel** [vlang/website#38]
With Opera 60.0 on Windows 8:
![image](https://user-images.githubusercontent.com/1107820/60755981-94905d80-9fef-11e9-9e70-4c6b77bf7506.png)

**Comment by medvednikov** [comment]
Is it still a problem?

What's the size of your screen?

**Comment by ntrel** [comment]
It is still the same with Opera - with a maximized Window it looks OK as the language list is next to the language documentation section links. But if I make the Window width 90% then I see the same as the screenshot. My resolution is 1280 x 1024. (BTW the screenshot I downscaled to save bandwidth, maybe that made it look like a low resolution). With Chrome it's OK, the language list is above "The V Programming Language" heading text.

**Comment by medvednikov** [comment]
Strange, Opera is pretty much Chrome, they should be the same.

**Comment by medvednikov** [comment]
Fixed.
