### ISSUE TITLE
nim

### ISSUE THREAD

**Issue by benman1** [vlang/website#53]
Hi!
I am just going over the comparison table. It compiles some of the most useful data. 

Just some comments: 

* Perhaps GC, REPL, and package managers could be included? 
* Crystal is perhaps in a similar space as nim and V - I'd love to see it included in the comparison. Crystal is designed around coroutines and offers [very easy C bindings](https://crystal-lang.org/reference/syntax_and_semantics/c_bindings/).
* nim supports [cross-compilation](https://nim-lang.org/docs/nimc.html#cross-compilation)
* nim uses async-await to achieve concurrency
* In C/C++ or any language with easy C interoperability you can use openmp for high-performance concurrency/shared memory multiprocessing. C++20 brings [co_await, co_yield and other keywords](https://en.cppreference.com/w/cpp/language/coroutines) for coroutines.

**Comment by medvednikov** [comment]
From Nim cross compilation docs you referenced:

> Then move the C code and the compile script compile_myproject.sh to your Linux i386 machine and run the script.

This is not cross compiling :)

**Comment by medvednikov** [comment]
I don't think async/await make concurrency simple, quite the opposite.

I don't want to do lots of comparisons, I'd rather list all the features and make it easy for the reader to compare to their favorite language.

**Comment by ntrel** [comment]
C++20 does not prevent low-level data races AFAIK (it doesn't have deep immutability or a memory-safe subset).
