### ISSUE TITLE
best method to document builtins?

### ISSUE THREAD

**Issue by tomByrer** [vlang/website#93]
Seems you have many helpful [builtins](https://github.com/vlang/v/tree/master/vlib/builtin)!

I thought of manually adding them to the website docs like I did for the symbols.  But we're programmers; we spend 20 hours automating a 4 hour manual documentation PR! ;)

A few ideas
 * Manual documentation is fastest at first, but expensive upkeep later.
 * Automation
    + I'm partial to [jsDoc comments](https://devhints.io/jsdoc) above the code, but it can be verbose as you repeat what the code does in comments
    + automated API cheatsheets; similar to [OpenAPI (Swagger)](https://swagger.io/specification/)
    + "Documentation Backend"  Instead of exporting JavaScript, C code,... you export documentation, or raw API docs (like a JSON tree or jsDocs file) that can be constructed by a tool to build the webpage.
    + using 'tests as documentation', alone or with a combination of the above.

Thanks!

**Comment by medvednikov** [comment]
The docs are generated from the comments via vdoc, just like in Go.

I need to release vdoc asap and update the docs.

**Comment by tomByrer** [comment]
Looking forward to the updated docs & `vdoc`; seems that built-ins is where half of the power lies.

**Comment by tomByrer** [comment]
Hopefully for version 0.2.1?  :D

**Comment by JalonSolov** [comment]
The new Modules page - https://modules.vlang.io/ - lists all the standard V modules.  `biltins` is right at the top.
That page is built with the new, updated `vdoc`.

**Comment by tomByrer** [comment]
Thanks!  A step in right direction.

Most don't have descriptions or demos though :/  Some that do can be confusing:

```c
compare_i64 #

fn compare_i64(a, b &i64) int

compare_i64 for []f64 sort_with_compare() sort []i64 with quicksort usage 
 mut x := [i64(100),10,70,28,92] x.sort_with_compare(compare_i64)
 println(x) // Sorted i64 Array output: [10, 28, 70, 92, 100]
```

**Comment by JalonSolov** [comment]
That's mainly a matter of getting more comments into the source.  The docs are built from the comments.  When you see something specific, it would be a good idea to enter an issue in the github vlang/v project, so it can be corrected via a source update.
