### ISSUE TITLE
use CSS instead of SCSS

### ISSUE THREAD

**Issue by tomByrer** [vlang/website#94]
Could I switch the SCSS to modern CSS with [custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) & [@import](https://developer.mozilla.org/en-US/docs/Web/CSS/@import).

The easier media queries with SCSS could be worked around with `env()` or a bit of V code ;)

Reasons: wanting to use [Cloudflare Workers](https://github.com/tomByrer/awesome-cloudflare-workers) or [raw.githack.com](https://raw.githack.com/vlang/website/master/docs.html) to serve the 'edge' version from master, easier to view files locally, don't have install overweight CSS transpliers, etc.

Only drawback might be a few selectors might not work on IE11, but any programmer worth his salt would avoid IE for their daily driver, correct?  👯‍♂

**Comment by Calinou** [comment]
The website appears to only use CSS now. This issue can probably be closed :slightly_smiling_face:
